import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DashboardWrapper from "./dashboard/dashboardWrapper";
import POSPanel from "./(components)/POSPanel.tsx/page";
import StoreProvider from "./redux";
import AuthInitializer from "@/app/(components)/AuthInitializer";
import { DebugRouter } from "./(components)/DebugRouter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FLOPPY IT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <AuthInitializer>
            <DebugRouter />
            <DashboardWrapper> 
              {children} 
              <POSPanel />
            </DashboardWrapper>
          </AuthInitializer>
        </StoreProvider>
      </body>
    </html>
  );
}